### ISSUE TITLE
avalanche targets cannot be observed

### ISSUE THREAD

**Issue by gnnx0425** [prometheus-community/avalanche#40]
I add the scrape_configs to prometheus configmap, checked that the configuration has been updated. But the new job always cannot be detect by Prometheus

Deployment file:

```
 #create namespace avalanche
apiVersion: v1
kind: Namespace
metadata:
  name: avalanche
spec:
  finalizers:
  -kubernetes


#create deployment avalanche
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: avalanche
  namespace: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: pg-avalanche
        image: quay.io/freshtracks.io/avalanche:latest
        args:
        - "--metric-count=1000"
        - "--series-count=50"
        - "--port=9001"
        ports:
        - containerPort: 9001

#create service avalanche-svc
apiVersion: v1
kind: Service
metadata:
  name: avalanche-svc
  namespace: avalanche
  labels:
    app: avalanche
spec:
  ports:
    # the port that this service should serve on
    - port: 9001
      targetPort: 9001
      name: http-avalanche
  type: ClusterIP
  clusterIP: None
  #label keys and values that must match in order to receive traffic for this service
  selector:
    app: avalanche


Scape_configs:
- job_name: ft-avalanche
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_avalanche_scrape] 
      action: keep
      regex: true  
```
