### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by Ellipse0934** [prometheus-community/avalanche#62]
Instead of linking to the [blog post](https://blog.freshtracks.io/load-testing-prometheus-metric-ingestion-5b878711711c) we should have basic usage instructions here itself. Because:
1. There is a discrepancy in the docker image url. Post suggests `freshtracks.io/avalanche` meanwhile the README gives `prometheuscommunity/avalanche`. I assume we want to suggest the latter.
2. The blogpost has images which cannot be copy pasted for convenience and must be manually written.
3. Editorial control should be maintained in the repo .

I'm happy to make a PR on this. I think we should suggest a compose file:
```yaml
version: "3.0"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/Prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prom
  avalanche:
    container_name: avalanche
    image: quay.io/prometheuscommunity/avalanche:main
    ports:
      - "9001:9001"
    networks:
      prom:
        aliases:
          - avalanche
networks:
  prom:
    name: prom
```
